name: CI Linux

on:
  workflow_call:

env:
  REPO_NAME: ${{ github.event.repository.name }}
  # Path where the module is installed with `v install <giturl>`
  MOD_PATH: ~/.vmodules/dialog

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Install V
        uses: vlang/setup-v@v1.3
        with:
          check-latest: true
      - name: Setup Dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libgtk-3-dev
          version: 1.0
      - name: Checkout ${{ env.REPO_NAME }}
        uses: actions/checkout@v3
        with:
          path: ${{ env.REPO_NAME }}
          submodules: true
      - name: Setup ${{ env.REPO_NAME }} as V module
        run: cp -r ${{ env.REPO_NAME }} ${{ env.MOD_PATH }}
      - name: Cache
        uses: actions/cache/save@v3
        with:
          path: |
            vlang
            ~/.vmodules
          key: ${{ runner.os }}-${{ github.sha }}

  lint:
    needs: setup
    uses: ./.github/workflows/lint.yml

  build:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [tcc, gcc, clang]
        optimization: ['', '-cstrict']
      fail-fast: false
    steps:
      - name: Restore Cache
        uses: actions/cache/restore@v3
        with:
          path: |
            vlang
            ~/.vmodules
          key: ${{ runner.os }}-${{ github.sha }}
          fail-on-cache-miss: true
      - name: Setup V
        uses: vlang/setup-v@v1.3
      - name: Setup Dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libgtk-3-dev
          version: 1.0
      - name: Build
        run: v -cg -cc ${{ matrix.compiler }} ${{ env.MOD_PATH }}/examples/minimal.v
